import { useState } from "react";
import { ArrowRight, CheckCircle2, Github, Linkedin, Mail, type LucideIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Section, SectionHeading } from "./Section";
type FormState={name:string;email:string;company:string;subject:string;message:string};
const empty:FormState={name:"",email:"",company:"",subject:"",message:""};
const contactLinks: { icon: LucideIcon; label: string; value: string }[] = [{icon:Mail,label:"E-mail",value:"alex.martins@techvision.dev"},{icon:Linkedin,label:"LinkedIn",value:"linkedin.com/in/alexmartins"},{icon:Github,label:"GitHub",value:"github.com/alexmartins"}];
export function Contact(){const[data,setData]=useState(empty);const[errors,setErrors]=useState<Partial<Record<keyof FormState,string>>>({});const[sent,setSent]=useState(false);
function submit(e:React.FormEvent){e.preventDefault();const next:typeof errors={};if(data.name.trim().length<2)next.name="Informe seu nome.";if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email.trim()))next.email="Informe um e-mail válido.";if(data.subject.trim().length<3)next.subject="Informe o assunto.";if(data.message.trim().length<10)next.message="Escreva pelo menos 10 caracteres.";setErrors(next);if(Object.keys(next).length===0){setSent(true);setData(empty)}}
const update=(key:keyof FormState,value:string)=>{setData(v=>({...v,[key]:value}));setErrors(v=>({...v,[key]:undefined}));setSent(false)};
return <Section id="contato"><div className="grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><SectionHeading eyebrow="07 / CONTATO" title="Vamos transformar uma ideia em solução?" copy="Tem um projeto, processo ou problema que pode ser melhorado através da tecnologia? Entre em contato."/><div className="space-y-3">{contactLinks.map(({icon:Icon,label,value})=><div className="contact-line" key={label}><Icon/><div><span>{label}</span><p>{value}</p></div></div>)}</div><p className="mt-6 text-xs text-muted-foreground">Dados de contato fictícios para demonstração.</p></div><form className="contact-form" onSubmit={submit} noValidate>{sent&&<div className="success-message" role="status"><CheckCircle2/> Mensagem simulada com sucesso. Obrigado pelo contato!</div>}<div className="grid gap-5 sm:grid-cols-2"><Field label="Nome" error={errors.name}><Input value={data.name} onChange={e=>update("name",e.target.value)} maxLength={100} autoComplete="name" placeholder="Seu nome" aria-invalid={!!errors.name}/></Field><Field label="E-mail" error={errors.email}><Input value={data.email} onChange={e=>update("email",e.target.value)} maxLength={255} type="email" autoComplete="email" placeholder="voce@empresa.com" aria-invalid={!!errors.email}/></Field><Field label="Empresa"><Input value={data.company} onChange={e=>update("company",e.target.value)} maxLength={100} autoComplete="organization" placeholder="Nome da empresa (opcional)"/></Field><Field label="Assunto" error={errors.subject}><Input value={data.subject} onChange={e=>update("subject",e.target.value)} maxLength={120} placeholder="Como posso ajudar?" aria-invalid={!!errors.subject}/></Field></div><Field label="Mensagem" error={errors.message}><Textarea value={data.message} onChange={e=>update("message",e.target.value)} maxLength={1000} rows={6} placeholder="Conte um pouco sobre sua ideia ou desafio..." aria-invalid={!!errors.message}/></Field><Button variant="hero" size="lg" type="submit">Enviar mensagem <ArrowRight/></Button></form></div></Section>}
function Field({label,error,children}:{label:string;error?:string|undefined;children:React.ReactNode}){return <label className="field-label"><span>{label}</span>{children}{error&&<small role="alert">{error}</small>}</label>}
